# Generated by Django 6.0.2 on 2026-03-15 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_count', models.IntegerField()),
                ('cars_valor', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=200)),
                ('fabricado_em', models.IntegerField(blank=True, null=True)),
                ('ano_modelo', models.IntegerField(blank=True, null=True)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_marca', to='cars.marca')),
            ],
        ),
    ]
